services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    volumes:
      - ./app:/app/app
    environment:
      - ENVIRONMENT=development
      - LOG_LEVEL=debug
    restart: unless-stopped
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "80", "--reload"]